plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
title: Hazard Detection in Self-driving Vehicles
description: Created by Sabrina Wu, Viet Luong, and Matthew Zietz
include:
  - README.md
  - webpage.md
theme: jekyll-theme-tactile
